---
# tasks file for libvirt (Ubuntu specific)

- name: Install libvirt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - "{{ libvirt_packages }}"
  tags:
    - libvirt
